# Generated by Django 3.1 on 2020-09-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Status',
        ),
        migrations.AddField(
            model_name='user',
            name='Size',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
