# Generated by Django 3.1 on 2020-09-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200924_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Status',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
